version: "3.8"

services:
  pumpmonitor:
    build: .
    container_name: pumpmonitor
    environment:
       PG_HOST: $PG_HOST
       PG_PORT: $PG_PORT
       PG_DATABASE: $PG_DATABASE
       PG_USER: $PG_USER
       PG_PASSWORD: $PG_PASSWORD
    restart: unless-stopped
    networks:
       - web

networks:
  web:
    external: true
    name: web