version: "3.8"

services:
  pumpmonitor:
    build: .
    container_name: pumpmonitor
    environment:
       PG_HOST: $PG_HOST
       PG_PORT: $PG_PORT
       PG_DATABASE: $PG_DATABASE
       PG_USER: $PG_USER
       PG_PASSWORD: $PG_PASSWORD
       SOLANA_NODE_RPC_ENDPOINT: $SOLANA_NODE_RPC_ENDPOINT
       SOLANA_NODE_WSS_ENDPOINT: $SOLANA_NODE_WSS_ENDPOINT
    restart: unless-stopped
    networks:
       - web

networks:
  web:
    external: true
    name: web